// <auto-generated />
using System;
using LogisticaHospitalaria_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogisticaHospitalaria_Backend.Migrations
{
    [DbContext(typeof(LogisticaHospitalariaContext))]
    [Migration("20260504211704_AgregarCodigoDepartamento")]
    partial class AgregarCodigoDepartamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartamentoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("text");

                    b.HasKey("DepartamentoId");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            DepartamentoId = 1,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Gestión de Pacientes",
                            PublicId = new Guid("acc04347-f411-432b-b7e2-5784482a8f5d")
                        },
                        new
                        {
                            DepartamentoId = 2,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Emergencias y Triaje",
                            PublicId = new Guid("55e84de0-4de1-49f8-9cb9-5e5fc3f4a419")
                        },
                        new
                        {
                            DepartamentoId = 3,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Consultas Externas",
                            PublicId = new Guid("6ead7d3a-8ad1-4fbb-be55-62bb2c7dd812")
                        },
                        new
                        {
                            DepartamentoId = 4,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Hospitalización",
                            PublicId = new Guid("ec9aab9d-b89d-428b-8ad9-5d39aaef8982")
                        },
                        new
                        {
                            DepartamentoId = 5,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Cuidados Críticos",
                            PublicId = new Guid("7be3408a-b014-4dbe-bf4d-0e5a051ed37b")
                        },
                        new
                        {
                            DepartamentoId = 6,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Gestión Quirúrgica",
                            PublicId = new Guid("0f0e7a13-84f9-492f-8727-42dde8736f53")
                        },
                        new
                        {
                            DepartamentoId = 7,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Especialidades Médicas",
                            PublicId = new Guid("a350f35a-9990-4532-ab8d-b4ae3d8f3d4d")
                        },
                        new
                        {
                            DepartamentoId = 8,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Diagnóstico Clínico",
                            PublicId = new Guid("a23bde86-1aab-4fe7-803e-d21ebdc9cfa2")
                        },
                        new
                        {
                            DepartamentoId = 9,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Diagnóstico por Imágenes",
                            PublicId = new Guid("8965e0af-61f0-4095-9388-652e8a370d0e")
                        },
                        new
                        {
                            DepartamentoId = 10,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Farmacia Hospitalaria",
                            PublicId = new Guid("b0d8f384-d257-400d-82af-047583d5fa54")
                        },
                        new
                        {
                            DepartamentoId = 11,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Terapias y Rehabilitación",
                            PublicId = new Guid("3d7a7d53-11bd-4c98-a784-6c25b44fb7c0")
                        },
                        new
                        {
                            DepartamentoId = 12,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Maternidad y Neonatología",
                            PublicId = new Guid("85dc041c-d0ca-4e1f-9353-27da7035e88e")
                        },
                        new
                        {
                            DepartamentoId = 13,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Gestión de Enfermería",
                            PublicId = new Guid("2ca45482-ed98-4120-9b44-c42d42498af7")
                        },
                        new
                        {
                            DepartamentoId = 14,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Gestión de Turnos y Citas",
                            PublicId = new Guid("9417c3e3-c6b9-421f-af13-fb901388df5f")
                        },
                        new
                        {
                            DepartamentoId = 15,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Facturación y Seguros",
                            PublicId = new Guid("d83cca99-9331-4e64-a9b0-9faaaaa78a05")
                        },
                        new
                        {
                            DepartamentoId = 16,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Recursos Humanos",
                            PublicId = new Guid("69e3a98f-4fb8-4c52-a2f6-0c2ef4ddbb33")
                        },
                        new
                        {
                            DepartamentoId = 17,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Gestión Financiera",
                            PublicId = new Guid("6c33ac9e-1975-446f-a762-f935d95a201b")
                        },
                        new
                        {
                            DepartamentoId = 18,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Compras y Abastecimiento",
                            PublicId = new Guid("c14e1cb1-b2c8-44d5-8c25-d84c47f31d41")
                        },
                        new
                        {
                            DepartamentoId = 19,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Gestión de Inventarios",
                            PublicId = new Guid("4836422e-4b58-408c-81a1-1179d45a4347")
                        },
                        new
                        {
                            DepartamentoId = 20,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Mantenimiento y Activos",
                            PublicId = new Guid("f5522698-03b9-4c64-ac24-11ee0ec6911c")
                        },
                        new
                        {
                            DepartamentoId = 21,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Soporte Técnico TI",
                            PublicId = new Guid("05835c9b-6803-41de-88c3-b13770a1cca9")
                        },
                        new
                        {
                            DepartamentoId = 22,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Gestión de Calidad",
                            PublicId = new Guid("ba830628-948e-4a29-808e-88bb28af7e05")
                        },
                        new
                        {
                            DepartamentoId = 23,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Bioseguridad y Control Sanitario",
                            PublicId = new Guid("0018a954-8d8e-47d4-b34f-9e75ff45cc69")
                        },
                        new
                        {
                            DepartamentoId = 24,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Investigación Clínica",
                            PublicId = new Guid("d5860ade-7211-4c55-b358-eb985bd05cd9")
                        },
                        new
                        {
                            DepartamentoId = 25,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Docencia y Capacitación",
                            PublicId = new Guid("0f42fe98-12a8-44a5-bbb9-ad9fe2f251fa")
                        },
                        new
                        {
                            DepartamentoId = 26,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Gestión Legal",
                            PublicId = new Guid("94d05067-0ce8-406a-ab5c-6601804005a2")
                        },
                        new
                        {
                            DepartamentoId = 27,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Atención al Paciente",
                            PublicId = new Guid("76657e1f-3026-4193-8764-92cf83b8c787")
                        },
                        new
                        {
                            DepartamentoId = 28,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Telemedicina",
                            PublicId = new Guid("3fd69305-9131-4a20-a905-ebed1296fea8")
                        },
                        new
                        {
                            DepartamentoId = 29,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Analítica y Reportes BI",
                            PublicId = new Guid("c0222063-314e-41f9-b0f6-d80f428fc200")
                        },
                        new
                        {
                            DepartamentoId = 30,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Seguridad y Accesos",
                            PublicId = new Guid("6a32418b-baab-47bf-8ffa-cedaaa180533")
                        },
                        new
                        {
                            DepartamentoId = 31,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Interoperabilidad e Integración",
                            PublicId = new Guid("99d881f4-3731-407a-80c6-2ea3320a558a")
                        },
                        new
                        {
                            DepartamentoId = 32,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Gestión Documental",
                            PublicId = new Guid("839ee6a8-9a4e-4c91-bd99-cccf17c13b23")
                        },
                        new
                        {
                            DepartamentoId = 33,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Logística Hospitalaria",
                            PublicId = new Guid("2a100641-2617-4102-83fd-b2ffe9e726a9")
                        },
                        new
                        {
                            DepartamentoId = 34,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Gestión de Ambulancias",
                            PublicId = new Guid("6b569618-80f1-4a0f-8c69-4860c8830d77")
                        },
                        new
                        {
                            DepartamentoId = 35,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Control Epidemiológico",
                            PublicId = new Guid("078ebdb4-4202-491e-988b-1445d08bab52")
                        },
                        new
                        {
                            DepartamentoId = 36,
                            Activo = true,
                            Codigo = "",
                            Nombre = "Psicología",
                            PublicId = new Guid("1d2a1583-80b1-4641-a32c-1a6ec687ff0d")
                        });
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.DetalleSolicitud", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetalleId"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("ItemNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer");

                    b.Property<string>("Unidad")
                        .HasColumnType("text");

                    b.HasKey("DetalleId");

                    b.HasIndex("SolicitudId");

                    b.ToTable("DetallesSolicitud");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.HistorialSolicitud", b =>
                {
                    b.Property<int>("HistorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistorialId"));

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("HistorialId");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialSolicitudes");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Solicitud", b =>
                {
                    b.Property<int>("SolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SolicitudId"));

                    b.Property<int?>("DepartamentoDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaAceptacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaRequerida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoSolicitudId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioResponsableId")
                        .HasColumnType("integer");

                    b.HasKey("SolicitudId");

                    b.HasIndex("DepartamentoDestinoId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("TipoSolicitudId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioResponsableId");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.TipoDepartamento", b =>
                {
                    b.Property<int>("TipoDepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoDepartamentoId"));

                    b.Property<int>("DepartamentoDuenoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoSolicitudId")
                        .HasColumnType("integer");

                    b.HasKey("TipoDepartamentoId");

                    b.HasIndex("DepartamentoDuenoId");

                    b.HasIndex("TipoSolicitudId");

                    b.ToTable("TiposDepartamento");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.TipoSolicitud", b =>
                {
                    b.Property<int>("TipoSolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoSolicitudId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.HasKey("TipoSolicitudId");

                    b.ToTable("TiposSolicitud");

                    b.HasData(
                        new
                        {
                            TipoSolicitudId = 1,
                            Activo = true,
                            Categoria = "Insumo",
                            Nombre = "Insumos Médicos",
                            PublicId = new Guid("921138c7-2edc-4715-816c-681a491bb5b7")
                        },
                        new
                        {
                            TipoSolicitudId = 2,
                            Activo = true,
                            Categoria = "Insumo",
                            Nombre = "Medicamentos",
                            PublicId = new Guid("c41a7cd5-37ec-4eb5-870c-69330d2420a5")
                        },
                        new
                        {
                            TipoSolicitudId = 3,
                            Activo = true,
                            Categoria = "Insumo",
                            Nombre = "Equipamiento",
                            PublicId = new Guid("9b3656d6-2a27-4390-86ab-cb58f479978a")
                        },
                        new
                        {
                            TipoSolicitudId = 4,
                            Activo = true,
                            Categoria = "Servicio",
                            Nombre = "Mantenimiento",
                            PublicId = new Guid("f56a1192-e022-45a3-b511-be39ada6032b")
                        },
                        new
                        {
                            TipoSolicitudId = 5,
                            Activo = true,
                            Categoria = "Traslado",
                            Nombre = "Traslado de Materiales",
                            PublicId = new Guid("dfa5473c-fc48-4b51-96bf-4b0fb3385677")
                        },
                        new
                        {
                            TipoSolicitudId = 6,
                            Activo = true,
                            Categoria = "Servicio",
                            Nombre = "Reunión",
                            PublicId = new Guid("461f8e7c-9925-4e21-a8ba-c563c4f8bbdb")
                        },
                        new
                        {
                            TipoSolicitudId = 7,
                            Activo = true,
                            Categoria = "Servicio",
                            Nombre = "Permiso",
                            PublicId = new Guid("c6cde35e-f832-4b4e-b782-5dcd63ffb913")
                        });
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenciaRRHH")
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UsuarioId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.WebhookSuscriptor", b =>
                {
                    b.Property<int>("WebhookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WebhookId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreSistema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecretoFirma")
                        .HasColumnType("text");

                    b.Property<string>("UrlCallback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WebhookId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("WebhookSuscriptores");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.DetalleSolicitud", b =>
                {
                    b.HasOne("LogisticaHospitalaria_Backend.Models.Solicitud", "Solicitud")
                        .WithMany("Detalles")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.HistorialSolicitud", b =>
                {
                    b.HasOne("LogisticaHospitalaria_Backend.Models.Solicitud", "Solicitud")
                        .WithMany("Historiales")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaHospitalaria_Backend.Models.Usuario", "Usuario")
                        .WithMany("Historiales")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Solicitud", b =>
                {
                    b.HasOne("Departamento", "DepartamentoDestino")
                        .WithMany()
                        .HasForeignKey("DepartamentoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Departamento", "Departamento")
                        .WithMany("Solicitudes")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogisticaHospitalaria_Backend.Models.TipoSolicitud", "TipoSolicitud")
                        .WithMany("Solicitudes")
                        .HasForeignKey("TipoSolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaHospitalaria_Backend.Models.Usuario", "Usuario")
                        .WithMany("Solicitudes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogisticaHospitalaria_Backend.Models.Usuario", "UsuarioResponsable")
                        .WithMany()
                        .HasForeignKey("UsuarioResponsableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departamento");

                    b.Navigation("DepartamentoDestino");

                    b.Navigation("TipoSolicitud");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioResponsable");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.TipoDepartamento", b =>
                {
                    b.HasOne("Departamento", "DepartamentoDueno")
                        .WithMany("TiposDepartamento")
                        .HasForeignKey("DepartamentoDuenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaHospitalaria_Backend.Models.TipoSolicitud", "TipoSolicitud")
                        .WithMany("TiposDepartamento")
                        .HasForeignKey("TipoSolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartamentoDueno");

                    b.Navigation("TipoSolicitud");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Usuario", b =>
                {
                    b.HasOne("Departamento", "Departamento")
                        .WithMany("Usuarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.WebhookSuscriptor", b =>
                {
                    b.HasOne("Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Departamento", b =>
                {
                    b.Navigation("Solicitudes");

                    b.Navigation("TiposDepartamento");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Solicitud", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Historiales");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.TipoSolicitud", b =>
                {
                    b.Navigation("Solicitudes");

                    b.Navigation("TiposDepartamento");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Usuario", b =>
                {
                    b.Navigation("Historiales");

                    b.Navigation("Solicitudes");
                });
#pragma warning restore 612, 618
        }
    }
}
