// <auto-generated />
using System;
using LogisticaHospitalaria_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogisticaHospitalaria_Backend.Migrations
{
    [DbContext(typeof(LogisticaHospitalariaContext))]
    [Migration("20260502061558_P1")]
    partial class P1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartamentoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.HasKey("DepartamentoId");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            DepartamentoId = 1,
                            Activo = true,
                            Nombre = "Gestión de Pacientes",
                            PublicId = new Guid("29bed892-6fc5-40e8-926c-ad7d9fdef6e5")
                        },
                        new
                        {
                            DepartamentoId = 2,
                            Activo = true,
                            Nombre = "Emergencias y Triaje",
                            PublicId = new Guid("cfea66d0-c03c-41c1-8d71-61d382b6a358")
                        },
                        new
                        {
                            DepartamentoId = 3,
                            Activo = true,
                            Nombre = "Consultas Externas",
                            PublicId = new Guid("01b9f986-4b4b-486f-815f-ad1b6e88c103")
                        },
                        new
                        {
                            DepartamentoId = 4,
                            Activo = true,
                            Nombre = "Hospitalización",
                            PublicId = new Guid("e6d56236-348b-45de-a6f6-2bae26b38c20")
                        },
                        new
                        {
                            DepartamentoId = 5,
                            Activo = true,
                            Nombre = "Cuidados Críticos",
                            PublicId = new Guid("9b7b593e-e592-4bcd-a624-c3894992a62f")
                        },
                        new
                        {
                            DepartamentoId = 6,
                            Activo = true,
                            Nombre = "Gestión Quirúrgica",
                            PublicId = new Guid("0168f5cf-b36e-4316-87a7-ffcd66f4d868")
                        },
                        new
                        {
                            DepartamentoId = 7,
                            Activo = true,
                            Nombre = "Especialidades Médicas",
                            PublicId = new Guid("361546a3-df8d-4f98-bc4d-fd07bf281b5e")
                        },
                        new
                        {
                            DepartamentoId = 8,
                            Activo = true,
                            Nombre = "Diagnóstico Clínico",
                            PublicId = new Guid("1345d33f-3b5f-4f6e-8b10-5a58740b0a83")
                        },
                        new
                        {
                            DepartamentoId = 9,
                            Activo = true,
                            Nombre = "Diagnóstico por Imágenes",
                            PublicId = new Guid("7b906583-22da-4462-9b89-8f415abdf6a8")
                        },
                        new
                        {
                            DepartamentoId = 10,
                            Activo = true,
                            Nombre = "Farmacia Hospitalaria",
                            PublicId = new Guid("ec4f7443-15c7-40d9-87dd-23721c6e4353")
                        },
                        new
                        {
                            DepartamentoId = 11,
                            Activo = true,
                            Nombre = "Terapias y Rehabilitación",
                            PublicId = new Guid("2ac07d0b-0e26-4e43-9ec3-8372b6df0cbb")
                        },
                        new
                        {
                            DepartamentoId = 12,
                            Activo = true,
                            Nombre = "Maternidad y Neonatología",
                            PublicId = new Guid("3edcda48-55b1-4bd3-9bfc-1ef52e17ea86")
                        },
                        new
                        {
                            DepartamentoId = 13,
                            Activo = true,
                            Nombre = "Gestión de Enfermería",
                            PublicId = new Guid("f550de45-a01a-4634-862c-6d7fb1f87a1d")
                        },
                        new
                        {
                            DepartamentoId = 14,
                            Activo = true,
                            Nombre = "Gestión de Turnos y Citas",
                            PublicId = new Guid("686f43f3-cc15-4695-986a-397541315139")
                        },
                        new
                        {
                            DepartamentoId = 15,
                            Activo = true,
                            Nombre = "Facturación y Seguros",
                            PublicId = new Guid("abba0eff-b7d2-4ba9-aef9-6b9cac775678")
                        },
                        new
                        {
                            DepartamentoId = 16,
                            Activo = true,
                            Nombre = "Recursos Humanos",
                            PublicId = new Guid("741772c1-f2d2-466f-af13-ff0f2dea7df5")
                        },
                        new
                        {
                            DepartamentoId = 17,
                            Activo = true,
                            Nombre = "Gestión Financiera",
                            PublicId = new Guid("bbeae720-09a3-4fb5-83ae-319139974d33")
                        },
                        new
                        {
                            DepartamentoId = 18,
                            Activo = true,
                            Nombre = "Compras y Abastecimiento",
                            PublicId = new Guid("df17a08a-f5bd-44a5-b6a2-c78e24cdd794")
                        },
                        new
                        {
                            DepartamentoId = 19,
                            Activo = true,
                            Nombre = "Gestión de Inventarios",
                            PublicId = new Guid("c9b09bd6-5431-41b0-b17d-6356f72c217e")
                        },
                        new
                        {
                            DepartamentoId = 20,
                            Activo = true,
                            Nombre = "Mantenimiento y Activos",
                            PublicId = new Guid("d8466baa-7b84-49cc-8f78-90811988a644")
                        },
                        new
                        {
                            DepartamentoId = 21,
                            Activo = true,
                            Nombre = "Soporte Técnico TI",
                            PublicId = new Guid("c2fc2f71-3c4b-4b23-9a81-2207a950fb4d")
                        },
                        new
                        {
                            DepartamentoId = 22,
                            Activo = true,
                            Nombre = "Gestión de Calidad",
                            PublicId = new Guid("784ea619-b33a-41c8-94b9-093f990b53a2")
                        },
                        new
                        {
                            DepartamentoId = 23,
                            Activo = true,
                            Nombre = "Bioseguridad y Control Sanitario",
                            PublicId = new Guid("66cd33db-b676-45bc-ba69-2fe50fe74c84")
                        },
                        new
                        {
                            DepartamentoId = 24,
                            Activo = true,
                            Nombre = "Investigación Clínica",
                            PublicId = new Guid("955e792c-4445-48ed-9695-1fef8c48a944")
                        },
                        new
                        {
                            DepartamentoId = 25,
                            Activo = true,
                            Nombre = "Docencia y Capacitación",
                            PublicId = new Guid("7273b434-f8e2-4b3f-b682-6d9d5d452b83")
                        },
                        new
                        {
                            DepartamentoId = 26,
                            Activo = true,
                            Nombre = "Gestión Legal",
                            PublicId = new Guid("a84378a5-a23c-48cd-b967-634de18db853")
                        },
                        new
                        {
                            DepartamentoId = 27,
                            Activo = true,
                            Nombre = "Atención al Paciente",
                            PublicId = new Guid("f2983a41-7250-49a3-8895-be00b61675f4")
                        },
                        new
                        {
                            DepartamentoId = 28,
                            Activo = true,
                            Nombre = "Telemedicina",
                            PublicId = new Guid("71e61e91-7358-421b-a227-c6da6b539173")
                        },
                        new
                        {
                            DepartamentoId = 29,
                            Activo = true,
                            Nombre = "Analítica y Reportes BI",
                            PublicId = new Guid("7d4555f3-ec29-4214-9744-d609f0b646fe")
                        },
                        new
                        {
                            DepartamentoId = 30,
                            Activo = true,
                            Nombre = "Seguridad y Accesos",
                            PublicId = new Guid("1daba0d3-8ea4-46c3-bec3-d85eff214960")
                        },
                        new
                        {
                            DepartamentoId = 31,
                            Activo = true,
                            Nombre = "Interoperabilidad e Integración",
                            PublicId = new Guid("44930908-5eec-4bac-8031-60e08447c478")
                        },
                        new
                        {
                            DepartamentoId = 32,
                            Activo = true,
                            Nombre = "Gestión Documental",
                            PublicId = new Guid("96007c66-6703-4e40-a9c0-5175a6a619bf")
                        },
                        new
                        {
                            DepartamentoId = 33,
                            Activo = true,
                            Nombre = "Logística Hospitalaria",
                            PublicId = new Guid("b6815f6e-641e-41ef-a67b-f606802a1048")
                        },
                        new
                        {
                            DepartamentoId = 34,
                            Activo = true,
                            Nombre = "Gestión de Ambulancias",
                            PublicId = new Guid("ca718010-5db1-44ba-a4c9-3fe76fb20494")
                        },
                        new
                        {
                            DepartamentoId = 35,
                            Activo = true,
                            Nombre = "Control Epidemiológico",
                            PublicId = new Guid("312dc45d-2c09-4a56-8c48-09a8ae06bece")
                        },
                        new
                        {
                            DepartamentoId = 36,
                            Activo = true,
                            Nombre = "Psicología",
                            PublicId = new Guid("2e1aa3ec-9dd2-4e8e-999f-fc2036419a97")
                        });
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.HistorialSolicitud", b =>
                {
                    b.Property<int>("HistorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistorialId"));

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("HistorialId");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialSolicitudes");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Solicitud", b =>
                {
                    b.Property<int>("SolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SolicitudId"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaAceptacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoSolicitudId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioResponsableId")
                        .HasColumnType("integer");

                    b.HasKey("SolicitudId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("TipoSolicitudId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioResponsableId");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.TipoDepartamento", b =>
                {
                    b.Property<int>("TipoDepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoDepartamentoId"));

                    b.Property<int>("DepartamentoDuenoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoSolicitudId")
                        .HasColumnType("integer");

                    b.HasKey("TipoDepartamentoId");

                    b.HasIndex("DepartamentoDuenoId");

                    b.HasIndex("TipoSolicitudId");

                    b.ToTable("TiposDepartamento");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.TipoSolicitud", b =>
                {
                    b.Property<int>("TipoSolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoSolicitudId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.HasKey("TipoSolicitudId");

                    b.ToTable("TiposSolicitud");

                    b.HasData(
                        new
                        {
                            TipoSolicitudId = 1,
                            Activo = true,
                            Categoria = "Insumo",
                            Nombre = "Insumos Médicos",
                            PublicId = new Guid("6bfbf1dd-9bf7-4935-a713-21ee10b8ea09")
                        },
                        new
                        {
                            TipoSolicitudId = 2,
                            Activo = true,
                            Categoria = "Insumo",
                            Nombre = "Medicamentos",
                            PublicId = new Guid("40062c3e-7a0a-485a-a93c-5c596440581e")
                        },
                        new
                        {
                            TipoSolicitudId = 3,
                            Activo = true,
                            Categoria = "Equipo",
                            Nombre = "Equipamiento",
                            PublicId = new Guid("3a42082d-e46f-4d46-afbc-5360420ad49b")
                        },
                        new
                        {
                            TipoSolicitudId = 4,
                            Activo = true,
                            Categoria = "Servicio",
                            Nombre = "Mantenimiento",
                            PublicId = new Guid("7af6b2b4-97d7-4964-ba65-543ee0d07df7")
                        },
                        new
                        {
                            TipoSolicitudId = 5,
                            Activo = true,
                            Categoria = "Traslado",
                            Nombre = "Traslado de Materiales",
                            PublicId = new Guid("dabc5ff9-d4f6-4c4e-9ee7-f2374a2d606e")
                        });
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenciaRRHH")
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UsuarioId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.WebhookSuscriptor", b =>
                {
                    b.Property<int>("WebhookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WebhookId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreSistema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecretoFirma")
                        .HasColumnType("text");

                    b.Property<string>("UrlCallback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WebhookId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("WebhookSuscriptores");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.HistorialSolicitud", b =>
                {
                    b.HasOne("LogisticaHospitalaria_Backend.Models.Solicitud", "Solicitud")
                        .WithMany("Historiales")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaHospitalaria_Backend.Models.Usuario", "Usuario")
                        .WithMany("Historiales")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Solicitud", b =>
                {
                    b.HasOne("LogisticaHospitalaria_Backend.Models.Departamento", "Departamento")
                        .WithMany("Solicitudes")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaHospitalaria_Backend.Models.TipoSolicitud", "TipoSolicitud")
                        .WithMany("Solicitudes")
                        .HasForeignKey("TipoSolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaHospitalaria_Backend.Models.Usuario", "Usuario")
                        .WithMany("Solicitudes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogisticaHospitalaria_Backend.Models.Usuario", "UsuarioResponsable")
                        .WithMany()
                        .HasForeignKey("UsuarioResponsableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departamento");

                    b.Navigation("TipoSolicitud");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioResponsable");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.TipoDepartamento", b =>
                {
                    b.HasOne("LogisticaHospitalaria_Backend.Models.Departamento", "DepartamentoDueno")
                        .WithMany("TiposDepartamento")
                        .HasForeignKey("DepartamentoDuenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaHospitalaria_Backend.Models.TipoSolicitud", "TipoSolicitud")
                        .WithMany("TiposDepartamento")
                        .HasForeignKey("TipoSolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartamentoDueno");

                    b.Navigation("TipoSolicitud");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Usuario", b =>
                {
                    b.HasOne("LogisticaHospitalaria_Backend.Models.Departamento", "Departamento")
                        .WithMany("Usuarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.WebhookSuscriptor", b =>
                {
                    b.HasOne("LogisticaHospitalaria_Backend.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Departamento", b =>
                {
                    b.Navigation("Solicitudes");

                    b.Navigation("TiposDepartamento");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Solicitud", b =>
                {
                    b.Navigation("Historiales");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.TipoSolicitud", b =>
                {
                    b.Navigation("Solicitudes");

                    b.Navigation("TiposDepartamento");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Usuario", b =>
                {
                    b.Navigation("Historiales");

                    b.Navigation("Solicitudes");
                });
#pragma warning restore 612, 618
        }
    }
}
