// <auto-generated />
using System;
using LogisticaHospitalaria_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogisticaHospitalaria_Backend.Migrations
{
    [DbContext(typeof(LogisticaHospitalariaContext))]
    [Migration("20260504203136_AgregarUbicacion")]
    partial class AgregarUbicacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartamentoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("text");

                    b.HasKey("DepartamentoId");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            DepartamentoId = 1,
                            Activo = true,
                            Nombre = "Gestión de Pacientes",
                            PublicId = new Guid("487a416b-9f9a-4b7c-a211-76cfb343cd5d")
                        },
                        new
                        {
                            DepartamentoId = 2,
                            Activo = true,
                            Nombre = "Emergencias y Triaje",
                            PublicId = new Guid("7d99d970-60fa-4051-966c-4f964d577a59")
                        },
                        new
                        {
                            DepartamentoId = 3,
                            Activo = true,
                            Nombre = "Consultas Externas",
                            PublicId = new Guid("eccd9208-db34-4ee7-8ae3-a32b7129decf")
                        },
                        new
                        {
                            DepartamentoId = 4,
                            Activo = true,
                            Nombre = "Hospitalización",
                            PublicId = new Guid("afc54b99-a6e1-4457-8a38-a746e1d87a5b")
                        },
                        new
                        {
                            DepartamentoId = 5,
                            Activo = true,
                            Nombre = "Cuidados Críticos",
                            PublicId = new Guid("c42b4187-5bfd-4e06-b4e7-efec715644ea")
                        },
                        new
                        {
                            DepartamentoId = 6,
                            Activo = true,
                            Nombre = "Gestión Quirúrgica",
                            PublicId = new Guid("da70aa48-05f9-4552-b057-96a1f4a69cf8")
                        },
                        new
                        {
                            DepartamentoId = 7,
                            Activo = true,
                            Nombre = "Especialidades Médicas",
                            PublicId = new Guid("ca421660-185e-4480-9a71-6f894c20e67b")
                        },
                        new
                        {
                            DepartamentoId = 8,
                            Activo = true,
                            Nombre = "Diagnóstico Clínico",
                            PublicId = new Guid("aa7b1c1c-e46e-48fc-b981-c29aef512075")
                        },
                        new
                        {
                            DepartamentoId = 9,
                            Activo = true,
                            Nombre = "Diagnóstico por Imágenes",
                            PublicId = new Guid("c9329dcf-69bf-4b41-bdb9-a489941d2fe2")
                        },
                        new
                        {
                            DepartamentoId = 10,
                            Activo = true,
                            Nombre = "Farmacia Hospitalaria",
                            PublicId = new Guid("893b9b4e-9e13-4a82-9d75-e788a895757b")
                        },
                        new
                        {
                            DepartamentoId = 11,
                            Activo = true,
                            Nombre = "Terapias y Rehabilitación",
                            PublicId = new Guid("e97c03f0-c79b-431e-a1ad-3989aa6b4bf6")
                        },
                        new
                        {
                            DepartamentoId = 12,
                            Activo = true,
                            Nombre = "Maternidad y Neonatología",
                            PublicId = new Guid("1d65283c-5b7a-4cef-8ceb-18a5b36c337a")
                        },
                        new
                        {
                            DepartamentoId = 13,
                            Activo = true,
                            Nombre = "Gestión de Enfermería",
                            PublicId = new Guid("7879b33c-d4c4-44b3-8d68-01f64d9e3842")
                        },
                        new
                        {
                            DepartamentoId = 14,
                            Activo = true,
                            Nombre = "Gestión de Turnos y Citas",
                            PublicId = new Guid("26c5b525-0522-45c0-832c-c98dd2f680f1")
                        },
                        new
                        {
                            DepartamentoId = 15,
                            Activo = true,
                            Nombre = "Facturación y Seguros",
                            PublicId = new Guid("e88bb420-a646-4e81-a304-d07541ca8cdd")
                        },
                        new
                        {
                            DepartamentoId = 16,
                            Activo = true,
                            Nombre = "Recursos Humanos",
                            PublicId = new Guid("fb5056bf-a672-47d1-a1c7-bf34a3cc6fef")
                        },
                        new
                        {
                            DepartamentoId = 17,
                            Activo = true,
                            Nombre = "Gestión Financiera",
                            PublicId = new Guid("dc9be65a-a28e-4911-bd8a-6e7681ffac8a")
                        },
                        new
                        {
                            DepartamentoId = 18,
                            Activo = true,
                            Nombre = "Compras y Abastecimiento",
                            PublicId = new Guid("ec3b4a66-2943-4c84-a517-fd5653979528")
                        },
                        new
                        {
                            DepartamentoId = 19,
                            Activo = true,
                            Nombre = "Gestión de Inventarios",
                            PublicId = new Guid("ebebb9fc-e04c-45ae-8816-7e3063102b8c")
                        },
                        new
                        {
                            DepartamentoId = 20,
                            Activo = true,
                            Nombre = "Mantenimiento y Activos",
                            PublicId = new Guid("5e295500-129e-4922-9615-17c99dc64b94")
                        },
                        new
                        {
                            DepartamentoId = 21,
                            Activo = true,
                            Nombre = "Soporte Técnico TI",
                            PublicId = new Guid("b273f8c1-b23c-471e-8301-a1ddb4ae4f38")
                        },
                        new
                        {
                            DepartamentoId = 22,
                            Activo = true,
                            Nombre = "Gestión de Calidad",
                            PublicId = new Guid("e9ea1c03-07fd-4944-b92a-2f4f5ba39ade")
                        },
                        new
                        {
                            DepartamentoId = 23,
                            Activo = true,
                            Nombre = "Bioseguridad y Control Sanitario",
                            PublicId = new Guid("8c2c8881-d2a5-40e9-b93f-f5fbe575a5cb")
                        },
                        new
                        {
                            DepartamentoId = 24,
                            Activo = true,
                            Nombre = "Investigación Clínica",
                            PublicId = new Guid("8801fd2b-3318-4654-8a74-85b06a1c17b7")
                        },
                        new
                        {
                            DepartamentoId = 25,
                            Activo = true,
                            Nombre = "Docencia y Capacitación",
                            PublicId = new Guid("f4743716-02b6-4115-b479-178fac79ac8f")
                        },
                        new
                        {
                            DepartamentoId = 26,
                            Activo = true,
                            Nombre = "Gestión Legal",
                            PublicId = new Guid("3ffb7e44-2a97-4f5f-ba82-bbd61106e072")
                        },
                        new
                        {
                            DepartamentoId = 27,
                            Activo = true,
                            Nombre = "Atención al Paciente",
                            PublicId = new Guid("660d34e6-5e22-4128-8bfc-e0e90c24bb59")
                        },
                        new
                        {
                            DepartamentoId = 28,
                            Activo = true,
                            Nombre = "Telemedicina",
                            PublicId = new Guid("d64ff014-7798-444f-acc8-5f36898f75ae")
                        },
                        new
                        {
                            DepartamentoId = 29,
                            Activo = true,
                            Nombre = "Analítica y Reportes BI",
                            PublicId = new Guid("7d5b8d7b-77c7-48bb-8525-e0ed36efe5b2")
                        },
                        new
                        {
                            DepartamentoId = 30,
                            Activo = true,
                            Nombre = "Seguridad y Accesos",
                            PublicId = new Guid("6d1a088e-ae62-4b95-9795-77a3c92fd205")
                        },
                        new
                        {
                            DepartamentoId = 31,
                            Activo = true,
                            Nombre = "Interoperabilidad e Integración",
                            PublicId = new Guid("e404a7cf-b256-4a7a-a18f-26ace7201069")
                        },
                        new
                        {
                            DepartamentoId = 32,
                            Activo = true,
                            Nombre = "Gestión Documental",
                            PublicId = new Guid("8492c3a9-1404-418a-bd4f-ee38ed1704cf")
                        },
                        new
                        {
                            DepartamentoId = 33,
                            Activo = true,
                            Nombre = "Logística Hospitalaria",
                            PublicId = new Guid("8c3efd66-64b2-4a73-8c6e-da296122475b")
                        },
                        new
                        {
                            DepartamentoId = 34,
                            Activo = true,
                            Nombre = "Gestión de Ambulancias",
                            PublicId = new Guid("85750ed4-1c28-4dbb-b377-66fdac393f5b")
                        },
                        new
                        {
                            DepartamentoId = 35,
                            Activo = true,
                            Nombre = "Control Epidemiológico",
                            PublicId = new Guid("0777b4e4-0fad-49a7-89c8-6a9cc22a1cc0")
                        },
                        new
                        {
                            DepartamentoId = 36,
                            Activo = true,
                            Nombre = "Psicología",
                            PublicId = new Guid("5b5b341a-e4c0-4f1b-a5c1-ead9cbcf39be")
                        });
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.DetalleSolicitud", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetalleId"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("ItemNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer");

                    b.Property<string>("Unidad")
                        .HasColumnType("text");

                    b.HasKey("DetalleId");

                    b.HasIndex("SolicitudId");

                    b.ToTable("DetallesSolicitud");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.HistorialSolicitud", b =>
                {
                    b.Property<int>("HistorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistorialId"));

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("HistorialId");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialSolicitudes");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Solicitud", b =>
                {
                    b.Property<int>("SolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SolicitudId"));

                    b.Property<int?>("DepartamentoDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaAceptacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaRequerida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoSolicitudId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioResponsableId")
                        .HasColumnType("integer");

                    b.HasKey("SolicitudId");

                    b.HasIndex("DepartamentoDestinoId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("TipoSolicitudId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioResponsableId");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.TipoDepartamento", b =>
                {
                    b.Property<int>("TipoDepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoDepartamentoId"));

                    b.Property<int>("DepartamentoDuenoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoSolicitudId")
                        .HasColumnType("integer");

                    b.HasKey("TipoDepartamentoId");

                    b.HasIndex("DepartamentoDuenoId");

                    b.HasIndex("TipoSolicitudId");

                    b.ToTable("TiposDepartamento");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.TipoSolicitud", b =>
                {
                    b.Property<int>("TipoSolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoSolicitudId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.HasKey("TipoSolicitudId");

                    b.ToTable("TiposSolicitud");

                    b.HasData(
                        new
                        {
                            TipoSolicitudId = 1,
                            Activo = true,
                            Categoria = "Insumo",
                            Nombre = "Insumos Médicos",
                            PublicId = new Guid("da567cda-519f-4102-859c-0db7dcb9b2a9")
                        },
                        new
                        {
                            TipoSolicitudId = 2,
                            Activo = true,
                            Categoria = "Insumo",
                            Nombre = "Medicamentos",
                            PublicId = new Guid("a63c5a26-1781-40ec-a0e7-f91aef07b088")
                        },
                        new
                        {
                            TipoSolicitudId = 3,
                            Activo = true,
                            Categoria = "Insumo",
                            Nombre = "Equipamiento",
                            PublicId = new Guid("d0144e38-7303-495a-8c0a-bbc64a475075")
                        },
                        new
                        {
                            TipoSolicitudId = 4,
                            Activo = true,
                            Categoria = "Servicio",
                            Nombre = "Mantenimiento",
                            PublicId = new Guid("6c91a996-8053-4808-b021-469e422bd694")
                        },
                        new
                        {
                            TipoSolicitudId = 5,
                            Activo = true,
                            Categoria = "Traslado",
                            Nombre = "Traslado de Materiales",
                            PublicId = new Guid("3a6f0f4b-910b-4a04-bad4-99cc3505943f")
                        },
                        new
                        {
                            TipoSolicitudId = 6,
                            Activo = true,
                            Categoria = "Servicio",
                            Nombre = "Reunión",
                            PublicId = new Guid("0080ce83-705f-4ae7-8322-c32f8ee705c9")
                        },
                        new
                        {
                            TipoSolicitudId = 7,
                            Activo = true,
                            Categoria = "Servicio",
                            Nombre = "Permiso",
                            PublicId = new Guid("9bdf2954-6981-4573-b359-b756e9f2ecce")
                        });
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenciaRRHH")
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UsuarioId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.WebhookSuscriptor", b =>
                {
                    b.Property<int>("WebhookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WebhookId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreSistema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecretoFirma")
                        .HasColumnType("text");

                    b.Property<string>("UrlCallback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WebhookId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("WebhookSuscriptores");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.DetalleSolicitud", b =>
                {
                    b.HasOne("LogisticaHospitalaria_Backend.Models.Solicitud", "Solicitud")
                        .WithMany("Detalles")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.HistorialSolicitud", b =>
                {
                    b.HasOne("LogisticaHospitalaria_Backend.Models.Solicitud", "Solicitud")
                        .WithMany("Historiales")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaHospitalaria_Backend.Models.Usuario", "Usuario")
                        .WithMany("Historiales")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Solicitud", b =>
                {
                    b.HasOne("LogisticaHospitalaria_Backend.Models.Departamento", "DepartamentoDestino")
                        .WithMany()
                        .HasForeignKey("DepartamentoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LogisticaHospitalaria_Backend.Models.Departamento", "Departamento")
                        .WithMany("Solicitudes")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogisticaHospitalaria_Backend.Models.TipoSolicitud", "TipoSolicitud")
                        .WithMany("Solicitudes")
                        .HasForeignKey("TipoSolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaHospitalaria_Backend.Models.Usuario", "Usuario")
                        .WithMany("Solicitudes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogisticaHospitalaria_Backend.Models.Usuario", "UsuarioResponsable")
                        .WithMany()
                        .HasForeignKey("UsuarioResponsableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departamento");

                    b.Navigation("DepartamentoDestino");

                    b.Navigation("TipoSolicitud");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioResponsable");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.TipoDepartamento", b =>
                {
                    b.HasOne("LogisticaHospitalaria_Backend.Models.Departamento", "DepartamentoDueno")
                        .WithMany("TiposDepartamento")
                        .HasForeignKey("DepartamentoDuenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaHospitalaria_Backend.Models.TipoSolicitud", "TipoSolicitud")
                        .WithMany("TiposDepartamento")
                        .HasForeignKey("TipoSolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartamentoDueno");

                    b.Navigation("TipoSolicitud");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Usuario", b =>
                {
                    b.HasOne("LogisticaHospitalaria_Backend.Models.Departamento", "Departamento")
                        .WithMany("Usuarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.WebhookSuscriptor", b =>
                {
                    b.HasOne("LogisticaHospitalaria_Backend.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Departamento", b =>
                {
                    b.Navigation("Solicitudes");

                    b.Navigation("TiposDepartamento");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Solicitud", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Historiales");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.TipoSolicitud", b =>
                {
                    b.Navigation("Solicitudes");

                    b.Navigation("TiposDepartamento");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Usuario", b =>
                {
                    b.Navigation("Historiales");

                    b.Navigation("Solicitudes");
                });
#pragma warning restore 612, 618
        }
    }
}
