// <auto-generated />
using System;
using LogisticaHospitalaria_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogisticaHospitalaria_Backend.Migrations
{
    [DbContext(typeof(LogisticaHospitalariaContext))]
    [Migration("20260502072610_Arreglao")]
    partial class Arreglao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartamentoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.HasKey("DepartamentoId");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            DepartamentoId = 1,
                            Activo = true,
                            Nombre = "Gestión de Pacientes",
                            PublicId = new Guid("1bd3be45-83ee-411c-b3b3-7517baded477")
                        },
                        new
                        {
                            DepartamentoId = 2,
                            Activo = true,
                            Nombre = "Emergencias y Triaje",
                            PublicId = new Guid("45770547-3162-4606-a0ca-8a6c8283cfd8")
                        },
                        new
                        {
                            DepartamentoId = 3,
                            Activo = true,
                            Nombre = "Consultas Externas",
                            PublicId = new Guid("709124f5-bd71-4312-a350-c06dd44736db")
                        },
                        new
                        {
                            DepartamentoId = 4,
                            Activo = true,
                            Nombre = "Hospitalización",
                            PublicId = new Guid("2c055350-4870-4e29-85a1-5a866db6b256")
                        },
                        new
                        {
                            DepartamentoId = 5,
                            Activo = true,
                            Nombre = "Cuidados Críticos",
                            PublicId = new Guid("0f1640b6-1378-4016-b71f-f3688a19f784")
                        },
                        new
                        {
                            DepartamentoId = 6,
                            Activo = true,
                            Nombre = "Gestión Quirúrgica",
                            PublicId = new Guid("3e58d852-2dbd-4e82-8d1a-8d230713b84f")
                        },
                        new
                        {
                            DepartamentoId = 7,
                            Activo = true,
                            Nombre = "Especialidades Médicas",
                            PublicId = new Guid("bed59ed8-4119-41a8-8d12-3dc91c05ed06")
                        },
                        new
                        {
                            DepartamentoId = 8,
                            Activo = true,
                            Nombre = "Diagnóstico Clínico",
                            PublicId = new Guid("9e117609-a717-4506-8b0a-62c19942ecbd")
                        },
                        new
                        {
                            DepartamentoId = 9,
                            Activo = true,
                            Nombre = "Diagnóstico por Imágenes",
                            PublicId = new Guid("7913491d-8870-419e-a934-68663440efdb")
                        },
                        new
                        {
                            DepartamentoId = 10,
                            Activo = true,
                            Nombre = "Farmacia Hospitalaria",
                            PublicId = new Guid("936f1216-032d-4cb6-90fc-592eb1421736")
                        },
                        new
                        {
                            DepartamentoId = 11,
                            Activo = true,
                            Nombre = "Terapias y Rehabilitación",
                            PublicId = new Guid("92accf79-1da6-468a-a538-c4b9062fbe9a")
                        },
                        new
                        {
                            DepartamentoId = 12,
                            Activo = true,
                            Nombre = "Maternidad y Neonatología",
                            PublicId = new Guid("05ca69d3-35ac-4351-b073-9952126f0d3b")
                        },
                        new
                        {
                            DepartamentoId = 13,
                            Activo = true,
                            Nombre = "Gestión de Enfermería",
                            PublicId = new Guid("85594cba-d44b-4c44-9512-f9b893aa32f0")
                        },
                        new
                        {
                            DepartamentoId = 14,
                            Activo = true,
                            Nombre = "Gestión de Turnos y Citas",
                            PublicId = new Guid("1093333e-4d22-4fc6-8852-51b403555515")
                        },
                        new
                        {
                            DepartamentoId = 15,
                            Activo = true,
                            Nombre = "Facturación y Seguros",
                            PublicId = new Guid("c6554b4d-9d69-4f22-946e-d3cb041e21b2")
                        },
                        new
                        {
                            DepartamentoId = 16,
                            Activo = true,
                            Nombre = "Recursos Humanos",
                            PublicId = new Guid("155d6c2b-8e0d-45a6-87b3-2a7495c2bd90")
                        },
                        new
                        {
                            DepartamentoId = 17,
                            Activo = true,
                            Nombre = "Gestión Financiera",
                            PublicId = new Guid("cd142794-7e8c-4fa6-b356-a9a071fbec7e")
                        },
                        new
                        {
                            DepartamentoId = 18,
                            Activo = true,
                            Nombre = "Compras y Abastecimiento",
                            PublicId = new Guid("e9c610eb-93a1-4d34-b8bd-9f4e199c9fc4")
                        },
                        new
                        {
                            DepartamentoId = 19,
                            Activo = true,
                            Nombre = "Gestión de Inventarios",
                            PublicId = new Guid("5cbe24c3-07d0-4407-9fd4-514b0abc07c8")
                        },
                        new
                        {
                            DepartamentoId = 20,
                            Activo = true,
                            Nombre = "Mantenimiento y Activos",
                            PublicId = new Guid("8821bba3-5f94-4936-ac50-d436acc2b11c")
                        },
                        new
                        {
                            DepartamentoId = 21,
                            Activo = true,
                            Nombre = "Soporte Técnico TI",
                            PublicId = new Guid("02c9b0af-bf7a-4842-8fee-40a8a03cb520")
                        },
                        new
                        {
                            DepartamentoId = 22,
                            Activo = true,
                            Nombre = "Gestión de Calidad",
                            PublicId = new Guid("1f945fac-42dc-4a6b-b3a8-33f3e3447d7d")
                        },
                        new
                        {
                            DepartamentoId = 23,
                            Activo = true,
                            Nombre = "Bioseguridad y Control Sanitario",
                            PublicId = new Guid("0fffa1e1-3509-46a1-9e4e-f7aa61dc050c")
                        },
                        new
                        {
                            DepartamentoId = 24,
                            Activo = true,
                            Nombre = "Investigación Clínica",
                            PublicId = new Guid("2d3c3989-079d-4f61-83a5-0867edc94d14")
                        },
                        new
                        {
                            DepartamentoId = 25,
                            Activo = true,
                            Nombre = "Docencia y Capacitación",
                            PublicId = new Guid("30b44dda-d52c-4ade-9d62-8696a280215c")
                        },
                        new
                        {
                            DepartamentoId = 26,
                            Activo = true,
                            Nombre = "Gestión Legal",
                            PublicId = new Guid("92363890-3875-4574-a627-2b07f4e333eb")
                        },
                        new
                        {
                            DepartamentoId = 27,
                            Activo = true,
                            Nombre = "Atención al Paciente",
                            PublicId = new Guid("9fdccbb8-f4e9-4a06-9026-58ee19aa9f8f")
                        },
                        new
                        {
                            DepartamentoId = 28,
                            Activo = true,
                            Nombre = "Telemedicina",
                            PublicId = new Guid("e482105e-54f0-4cdb-bb23-ffa68d9f67a4")
                        },
                        new
                        {
                            DepartamentoId = 29,
                            Activo = true,
                            Nombre = "Analítica y Reportes BI",
                            PublicId = new Guid("eef73ae0-0522-40ca-b58e-3ad1b74a470e")
                        },
                        new
                        {
                            DepartamentoId = 30,
                            Activo = true,
                            Nombre = "Seguridad y Accesos",
                            PublicId = new Guid("bcf08965-db0b-4ba0-89aa-886691e73829")
                        },
                        new
                        {
                            DepartamentoId = 31,
                            Activo = true,
                            Nombre = "Interoperabilidad e Integración",
                            PublicId = new Guid("d9c6a554-3b99-4f75-a1f2-c729875571ef")
                        },
                        new
                        {
                            DepartamentoId = 32,
                            Activo = true,
                            Nombre = "Gestión Documental",
                            PublicId = new Guid("83f4df86-8135-4d0b-b2c3-aa0c554aee65")
                        },
                        new
                        {
                            DepartamentoId = 33,
                            Activo = true,
                            Nombre = "Logística Hospitalaria",
                            PublicId = new Guid("3b8c317f-6c3e-4a65-b419-89635218b363")
                        },
                        new
                        {
                            DepartamentoId = 34,
                            Activo = true,
                            Nombre = "Gestión de Ambulancias",
                            PublicId = new Guid("112101e0-feb6-498a-8202-21e4953a4ee3")
                        },
                        new
                        {
                            DepartamentoId = 35,
                            Activo = true,
                            Nombre = "Control Epidemiológico",
                            PublicId = new Guid("3c035a0c-9f6d-44f8-a6c9-88a43092630f")
                        },
                        new
                        {
                            DepartamentoId = 36,
                            Activo = true,
                            Nombre = "Psicología",
                            PublicId = new Guid("3579a608-bb22-4560-9b10-760e733e9944")
                        });
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.DetalleSolicitud", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetalleId"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("ItemNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer");

                    b.Property<string>("Unidad")
                        .HasColumnType("text");

                    b.HasKey("DetalleId");

                    b.HasIndex("SolicitudId");

                    b.ToTable("DetallesSolicitud");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.HistorialSolicitud", b =>
                {
                    b.Property<int>("HistorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistorialId"));

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("HistorialId");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialSolicitudes");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Solicitud", b =>
                {
                    b.Property<int>("SolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SolicitudId"));

                    b.Property<int?>("DepartamentoDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaAceptacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaRequerida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoSolicitudId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioResponsableId")
                        .HasColumnType("integer");

                    b.HasKey("SolicitudId");

                    b.HasIndex("DepartamentoDestinoId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("TipoSolicitudId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioResponsableId");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.TipoDepartamento", b =>
                {
                    b.Property<int>("TipoDepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoDepartamentoId"));

                    b.Property<int>("DepartamentoDuenoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoSolicitudId")
                        .HasColumnType("integer");

                    b.HasKey("TipoDepartamentoId");

                    b.HasIndex("DepartamentoDuenoId");

                    b.HasIndex("TipoSolicitudId");

                    b.ToTable("TiposDepartamento");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.TipoSolicitud", b =>
                {
                    b.Property<int>("TipoSolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoSolicitudId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.HasKey("TipoSolicitudId");

                    b.ToTable("TiposSolicitud");

                    b.HasData(
                        new
                        {
                            TipoSolicitudId = 1,
                            Activo = true,
                            Categoria = "Insumo",
                            Nombre = "Insumos Médicos",
                            PublicId = new Guid("c8feb700-1ef2-4a63-9485-8403c8a9bab9")
                        },
                        new
                        {
                            TipoSolicitudId = 2,
                            Activo = true,
                            Categoria = "Insumo",
                            Nombre = "Medicamentos",
                            PublicId = new Guid("ae9cba63-501f-4560-9d18-2c9ff2950d1a")
                        },
                        new
                        {
                            TipoSolicitudId = 3,
                            Activo = true,
                            Categoria = "Insumo",
                            Nombre = "Equipamiento",
                            PublicId = new Guid("9b8e491e-1466-42d3-a76c-f7517a4566d5")
                        },
                        new
                        {
                            TipoSolicitudId = 4,
                            Activo = true,
                            Categoria = "Servicio",
                            Nombre = "Mantenimiento",
                            PublicId = new Guid("d88f6332-32e6-4aaa-8b90-77501c57a337")
                        },
                        new
                        {
                            TipoSolicitudId = 5,
                            Activo = true,
                            Categoria = "Traslado",
                            Nombre = "Traslado de Materiales",
                            PublicId = new Guid("7100cf8c-ac55-41b0-b501-009f7358b08a")
                        },
                        new
                        {
                            TipoSolicitudId = 6,
                            Activo = true,
                            Categoria = "Servicio",
                            Nombre = "Reunión",
                            PublicId = new Guid("98bd8a9f-b89b-4948-8d4b-95b993f91244")
                        },
                        new
                        {
                            TipoSolicitudId = 7,
                            Activo = true,
                            Categoria = "Servicio",
                            Nombre = "Permiso",
                            PublicId = new Guid("9a37c4c6-1a4a-4a6a-bd20-38f92d85af17")
                        });
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenciaRRHH")
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UsuarioId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.WebhookSuscriptor", b =>
                {
                    b.Property<int>("WebhookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WebhookId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreSistema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecretoFirma")
                        .HasColumnType("text");

                    b.Property<string>("UrlCallback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WebhookId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("WebhookSuscriptores");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.DetalleSolicitud", b =>
                {
                    b.HasOne("LogisticaHospitalaria_Backend.Models.Solicitud", "Solicitud")
                        .WithMany("Detalles")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.HistorialSolicitud", b =>
                {
                    b.HasOne("LogisticaHospitalaria_Backend.Models.Solicitud", "Solicitud")
                        .WithMany("Historiales")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaHospitalaria_Backend.Models.Usuario", "Usuario")
                        .WithMany("Historiales")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Solicitud", b =>
                {
                    b.HasOne("LogisticaHospitalaria_Backend.Models.Departamento", "DepartamentoDestino")
                        .WithMany()
                        .HasForeignKey("DepartamentoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LogisticaHospitalaria_Backend.Models.Departamento", "Departamento")
                        .WithMany("Solicitudes")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogisticaHospitalaria_Backend.Models.TipoSolicitud", "TipoSolicitud")
                        .WithMany("Solicitudes")
                        .HasForeignKey("TipoSolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaHospitalaria_Backend.Models.Usuario", "Usuario")
                        .WithMany("Solicitudes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogisticaHospitalaria_Backend.Models.Usuario", "UsuarioResponsable")
                        .WithMany()
                        .HasForeignKey("UsuarioResponsableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departamento");

                    b.Navigation("DepartamentoDestino");

                    b.Navigation("TipoSolicitud");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioResponsable");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.TipoDepartamento", b =>
                {
                    b.HasOne("LogisticaHospitalaria_Backend.Models.Departamento", "DepartamentoDueno")
                        .WithMany("TiposDepartamento")
                        .HasForeignKey("DepartamentoDuenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaHospitalaria_Backend.Models.TipoSolicitud", "TipoSolicitud")
                        .WithMany("TiposDepartamento")
                        .HasForeignKey("TipoSolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartamentoDueno");

                    b.Navigation("TipoSolicitud");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Usuario", b =>
                {
                    b.HasOne("LogisticaHospitalaria_Backend.Models.Departamento", "Departamento")
                        .WithMany("Usuarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.WebhookSuscriptor", b =>
                {
                    b.HasOne("LogisticaHospitalaria_Backend.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Departamento", b =>
                {
                    b.Navigation("Solicitudes");

                    b.Navigation("TiposDepartamento");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Solicitud", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Historiales");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.TipoSolicitud", b =>
                {
                    b.Navigation("Solicitudes");

                    b.Navigation("TiposDepartamento");
                });

            modelBuilder.Entity("LogisticaHospitalaria_Backend.Models.Usuario", b =>
                {
                    b.Navigation("Historiales");

                    b.Navigation("Solicitudes");
                });
#pragma warning restore 612, 618
        }
    }
}
